### ISSUE TITLE
Build Fail in README example code  

### ISSUE THREAD

**Issue by dustintsao** [sohlich/elogrus#23] opened 2019-06-24 08:23 UTC
Hi, I try to build your README.md example code and got the following error,

./main.go:15:37: cannot use client (type *"gopkg.in/olivere/elastic.v5".Client) as type *"github.com/olivere/elastic".Client in argument to elogrus.NewElasticHook

How can I fix it?

**Comment by liuzoxan** [comment] 2019-08-01 09:48
Hi dustintsao,
I reproduced the error as yours. 

> cannot use client (type *"gopkg.in/olivere/elastic.v5".Client) as type *"github.com/olivere/elastic".Client in argument to elogrus.NewAsyncElasticHook

The problem is import package imcompatible：
Your code like this, I guess :-)
```go
import (
	"github.com/sirupsen/logrus"
	"gopkg.in/olivere/elastic.v5"
	"gopkg.in/sohlich/elogrus.v3"
)
```
The elogrus.v3 need elastic v6, elogrus.v2 need elastic v5. So the above elogrus v3 doesn't match witch elastic v5.

Later on, I will update the readme more clearly about the compatible problem. It is easy, but need to be clarified. 

Here is the working code you need.
```go
package main

import (
	"github.com/sirupsen/logrus"
	"gopkg.in/olivere/elastic.v5"
	"gopkg.in/sohlich/elogrus.v2"
)

func main() {
	log := logrus.New()
	client, err := elastic.NewClient(elastic.SetURL("http://localhost:9200"))
	if err != nil {
		log.Panic(err)
	}
	hook, err := elogrus.NewElasticHook(client, "localhost", logrus.DebugLevel, "mylog")
	if err != nil {
		log.Panic(err)
	}
	log.Hooks.Add(hook)

	log.WithFields(logrus.Fields{
		"name": "joe",
		"age":  42,
	}).Error("Hello world!")
}
```

**Comment by liuzoxan** [comment] 2019-08-05 08:23
I close this issue now. If still have problems, please re-open again. :-)

**Closed as completed by liuzoxan** 2019-08-05 08:23 UTC
